export const sprachen = {
  "Afrikaans": "af",
  "Albanisch": "sq",
  "Arabisch": "ar",
  "Aserbaidschanisch": "az",
  "Bengalisch": "bn",
  "Bulgarisch": "bg",
  "Chinesisch (Vereinfacht)": "zh-CN",
  "Chinesisch (Traditionell)": "zh-TW",
  "Dänisch": "da",
  "Deutsch": "de",
  "Englisch": "en",
  "Esperanto": "eo",
  "Estnisch": "et",
  "Finnisch": "fi",
  "Französisch": "fr",
  "Griechisch": "el",
  "Hebräisch": "he",
  "Hindi": "hi",
  "Indonesisch": "id",
  "Irisch": "ga",
  "Italienisch": "it",
  "Japanisch": "ja",
  "Koreanisch": "ko",
  "Kroatisch": "hr",
  "Lettisch": "lv",
  "Litauisch": "lt",
  "Malaiisch": "ms",
  "Niederländisch": "nl",
  "Norwegisch": "no",
  "Persisch (Farsi)": "fa",
  "Polnisch": "pl",
  "Portugiesisch (Portugal)": "pt-PT",
  "Portugiesisch (Brasilien)": "pt-BR",
  "Rumänisch": "ro",
  "Russisch": "ru",
  "Schwedisch": "sv",
  "Spanisch": "es",
  "Thai": "th",
  "Tschechisch": "cs",
  "Türkisch": "tr",
  "Ukrainisch": "uk",
  "Ungarisch": "hu",
  "Vietnamesisch": "vi"
};